### ISSUE TITLE
thread panic

### ISSUE THREAD

**Issue by 0323pin** [angelina-tsuboi/ctv#1] opened 2022-01-21 10:01 UTC
Hi,

Interesting project. I've just packaged and built `ctv` on my NetBSD machine.
Got the following warnings during compilation from source,

```
   Compiling ctv v0.1.4 (/usr/pkgsrc/wip/ctv/work/ctv-620562ff5aa6e92537b192f578e98467515b5665)
warning: unused import: `crate::input`
 --> src/protocols/file.rs:3:5
  |
3 | use crate::input;
  |     ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Path`
 --> src/protocols/dirtree.rs:1:17
  |
1 | use std::path::{Path, PathBuf};
  |                 ^^^^

warning: unused variable: `n`
   --> src/protocols/treegenerator.rs:142:13
    |
142 |         for n in 0..self.spacing {
    |             ^ help: if this is intentional, prefix it with an underscore: `_n`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:132:17
    |
128 |                   connector = &self.tee;
    |                               --------- immutable borrow occurs here
...
132 | /                 self.add_directory(
133 | |                     entry.path(), entry.path(), index, entries_count, prefix.to_string(), connector.to_string(), limit - 1
    | |                                                                                           --------------------- immutable borrow later used here
134 | |                 )
    | |_________________^ mutable borrow occurs here
    |
    = note: `#[warn(mutable_borrow_reservation_conflict)]` on by default
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:136:17
    |
128 |                 connector = &self.tee;
    |                             --------- immutable borrow occurs here
...
136 |                 self.add_file(entry.path(), prefix.to_string(), connector.to_string())
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------------^
    |                 |                                               |
    |                 |                                               immutable borrow later used here
    |                 mutable borrow occurs here
    |
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: variable does not need to be mutable
   --> src/protocols/treegenerator.rs:141:31
    |
141 |     fn add_spacing(&mut self, mut prefix: String) {
    |                               ----^^^^^^
    |                               |
    |                               help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: enum is never used: `DirSortType`
 --> src/protocols/file.rs:8:6
  |
8 | enum DirSortType {
  |      ^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: field is never read: `file_perms_color`
  --> src/protocols/file.rs:24:3
   |
24 |   file_perms_color: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `dir_name_style`
  --> src/protocols/file.rs:26:3
   |
26 |   dir_name_style: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `file_name_style`
  --> src/protocols/file.rs:27:3
   |
27 |   file_name_style: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `pipe`
  --> src/protocols/treegenerator.rs:11:5
   |
11 |     pipe: String,
   |     ^^^^^^^^^^^^

warning: `ctv` (bin "ctv") generated 11 warnings
    Finished release [optimized] target(s) in 12m 33s

```

Despite these warnings, it builds just fine.
Unfortunately, the resulting binary panics when launching it.
I get the following,

```
/home/pin()
2022-01-21 10:53 > RUST_BACKTRACE=full ctv -e ./Git/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/protocols/configmanager.rs:61:43
stack backtrace:
   0:        0x128536a86 - <unknown>
   1:        0x12856b60c - <unknown>
   2:        0x12852f465 - <unknown>
   3:        0x1285344d0 - <unknown>
   4:        0x128534071 - <unknown>
   5:        0x128534a83 - <unknown>
   6:        0x1285371f0 - <unknown>
   7:        0x128536bd4 - <unknown>
   8:        0x1285345c2 - <unknown>
   9:        0x12843c031 - <unknown>
  10:        0x12843c5b3 - <unknown>
  11:        0x128446426 - <unknown>
  12:        0x12845239d - <unknown>
  13:        0x1284552a3 - <unknown>
  14:        0x12844946d - <unknown>
  15:        0x12852b0e1 - <unknown>
  16:        0x1284530b2 - <unknown>
  17:        0x1284359ad - <unknown>
error: External command failed
   ┌─ shell:33:21
   │
33 │ RUST_BACKTRACE=full ctv -e ./Git/
   │                     ^^^ command failed

```
What am I missing? Some configuration needed?
Thanks!

**Comment by angelina-tsuboi** [comment] 2022-01-21 16:25
Thank you so much for letting me know @0323pin 
I think this issue has to do with the code using environment variables rather than a config file.
I'll try to fix this issue ASAP.
If you know how to fix this issue, please feel free to make a PR with the fixes.
Thanks!

**Comment by levone1** [comment] 2022-01-21 16:54
> Thank you so much for letting me know @0323pin I think this issue has to do with the code using environment variables rather than a config file. I'll try to fix this issue ASAP. If you know how to fix this issue, please feel free to make a PR with the fixes. Thanks!

I get panic/crash after successful compile / install via 'cargo install' on SailfishOS...  Likely same issue, or should I open new?

**Comment by angelina-tsuboi** [comment] 2022-01-21 17:16
@levone1 Yes, it is probably the same issue regarding the config file error.
When you use ctv outside its directory, is produces a panic error for all OS because it can not find the env file
I'll try to resolve this issue ASAP

**Comment by 0323pin** [comment] 2022-01-21 21:12
@angelina-tsuboi Unfortunately, I'm not a programmer , just a package maintainer. I haven't looked at the code yet but, I could try to help.

**Comment by angelina-tsuboi** [comment] 2022-01-21 22:08
@0323pin I think that is what the problem is. The code is trying to find the env file through a relative file path location rather than a global path environment like ~./config/ctv. I'll try implementing this into the code, and will let you know if it works

**Comment by 0323pin** [comment] 2022-01-21 22:27
@angelina-tsuboi just for info, I did create `~/.config/ctv` and copied the `.env` file into the directory. But, of course, if it doesn't look for the file there, it doesn't help :)

No worries, I know the project it's on its early days. Just so you know, I have no problem to do test builds.

**Comment by 0323pin** [comment] 2022-01-22 16:00
@angelina-tsuboi Some nice progress 👍 
Less warnings at build time,

```
   Compiling ctv v0.1.8 (/usr/pkgsrc/wip/ctv/work/ctv-b20b6dc53de1880545c0c3e0c8df02317b96fe0f)
warning: unused import: `dotenv::dotenv`
 --> src/protocols/configmanager.rs:2:5
  |
2 | use dotenv::dotenv;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:132:17
    |
128 |                   connector = &self.tee;
    |                               --------- immutable borrow occurs here
...
132 | /                 self.add_directory(
133 | |                     entry.path(), entry.path(), index, entries_count, prefix.to_string(), connector.to_string(), limit - 1
    | |                                                                                           --------------------- immutable borrow later used here
134 | |                 )
    | |_________________^ mutable borrow occurs here
    |
    = note: `#[warn(mutable_borrow_reservation_conflict)]` on by default
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:136:17
    |
128 |                 connector = &self.tee;
    |                             --------- immutable borrow occurs here
...
136 |                 self.add_file(entry.path(), prefix.to_string(), connector.to_string())
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------------^
    |                 |                                               |
    |                 |                                               immutable borrow later used here
    |                 mutable borrow occurs here
    |
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: field is never read: `file_perms_color`
  --> src/protocols/file.rs:14:3
   |
14 |   file_perms_color: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `dir_name_style`
  --> src/protocols/file.rs:16:3
   |
16 |   dir_name_style: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `file_name_style`
  --> src/protocols/file.rs:17:3
   |
17 |   file_name_style: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `pipe`
  --> src/protocols/treegenerator.rs:11:5
   |
11 |     pipe: String,
   |     ^^^^^^^^^^^^

warning: `ctv` (bin "ctv") generated 7 warnings
    Finished release [optimized] target(s) in 12m 53s

```

But, still thread panic,

```
/home/pin()
2022-01-22 16:55 > RUST_BACKTRACE=full ctv --set-env "DIR_COLOR=WHITE" ./Git/
done, "/home/pin/.cargo/registry/src/github.com-1ecc6299db9ec823/ctv-0.1.8/.env"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/protocols/configmanager.rs:65:43
stack backtrace:
   0:        0x1a6137eb6 - <unknown>
   1:        0x1a616ca8c - <unknown>
   2:        0x1a6130895 - <unknown>
   3:        0x1a6135900 - <unknown>
   4:        0x1a61354a1 - <unknown>
   5:        0x1a6135eb3 - <unknown>
   6:        0x1a6138620 - <unknown>
   7:        0x1a6138004 - <unknown>
   8:        0x1a61359f2 - <unknown>
   9:        0x1a603c251 - <unknown>
  10:        0x1a603c7d3 - <unknown>
  11:        0x1a6042791 - <unknown>
  12:        0x1a60546ad - <unknown>
  13:        0x1a6040fb3 - <unknown>
  14:        0x1a6045e1d - <unknown>
  15:        0x1a612c511 - <unknown>
  16:        0x1a60553c2 - <unknown>
  17:        0x1a6035bcd - <unknown>
error: External command failed
  ┌─ shell:8:21
  │
8 │ RUST_BACKTRACE=full ctv --set-env "DIR_COLOR=WHITE" ./Git/
  │                     ^^^ command failed

```

I'll keep testing.

**Comment by angelina-tsuboi** [comment] 2022-01-22 20:10
@0323pin Thanks for testing! It really helps. I'll keep tinkering with the code, and try to solve the panic issue

**Comment by 0323pin** [comment] 2022-01-22 20:34
@angelina-tsuboi As mentioned, I'll keep testing it, as much as needed. But, I wonder if I'm missing something.
Right now, I'm building from source and using pkgsrc framwork to install the resulting binary (target/release/ctv).
Should I install `.env` into some expected location? It still feels like I'm missing something?!

FYI, I won't be able to build anything for the next five hours or so, I'm building rust-1.58.1 right now.

**Comment by angelina-tsuboi** [comment] 2022-01-23 06:00
@0323pin I think it's more of an issue with the code. I figured out another way to get configuration working for this project that doesn't rely on a .env file. The feature is working right now, but I haven't published the changes yet because I still need to fix some bugs. I will finish it by tomorrow and will let you know when the changes are deployed, so you can test it on your machine. Stay tuned :)

**Comment by 0323pin** [comment] 2022-01-23 11:17
No problem, just let me know when to test it. Rust-1.58.1 build compleated.

**Comment by angelina-tsuboi** [comment] 2022-01-26 07:49
Hey @0323pin I was able to fix the issue by setting up a new functionality for configuring the tree view which involves the use of a **config.toml** file. ctv version 0.2.2 should now be working. Please read the README documentation on how to set up configuration styling / colors for your tree view! I will make a tutorial video and post it onto youtube if that is more helpful and attach the link to the README because setting up the config.toml is tedious, and a video could help some people who want to use ctv in the future

**Comment by 0323pin** [comment] 2022-01-26 08:25
@angelina-tsuboi Thanks!

It doesn't look to complicated, if I got it right.
I should have a configuration file as follows, `~/Library/Application_Support/dev.ctv.ctv/config.toml`

As for configuration in `toml`, I'm not to worried. I use `leftwm` as window manager and the configuration is also in `toml`, can hardly be worst that this, ~/Library/Application_Support/dev.ctv.ctv/config.toml 🤣 

I'll give it a go later today, at work right now.

**Comment by 0323pin** [comment] 2022-01-26 15:52
@angelina-tsuboi 

I've just built 0.2.2, different thread panic.
Thank you for your patience.

```
2022-01-26 16:47 > ctv -V
ctv 0.2.2
/home/pin()
2022-01-26 16:47 > RUST_BACKTRACE=full ctv
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/services/time.rs:21:51
stack backtrace:
   0:         0x840be736 - <unknown>
   1:         0x840f066c - <unknown>
   2:         0x840b46a5 - <unknown>
   3:         0x840b5680 - <unknown>
   4:         0x840b5221 - <unknown>
   5:         0x840b5ccb - <unknown>
   6:         0x840bee72 - <unknown>
   7:         0x840be884 - <unknown>
   8:         0x840b5772 - <unknown>
   9:         0x840154e1 - <unknown>
  10:         0x8401542d - <unknown>
  11:         0x8404d1f2 - <unknown>
  12:         0x8403c8bc - <unknown>
  13:         0x840496fa - <unknown>
  14:         0x8404789e - <unknown>
  15:         0x8404385a - <unknown>
  16:         0x84044d13 - <unknown>
  17:         0x8404adcd - <unknown>
  18:         0x840b1d21 - <unknown>
  19:         0x84044cd2 - <unknown>
  20:         0x84010a8d - <unknown>
error: External command failed
   ┌─ shell:39:21
   │
39 │ RUST_BACKTRACE=full ctv
   │                     ^^^ command failed

```

**Comment by angelina-tsuboi** [comment] 2022-01-26 16:44
@0323pin which path did you run the ctv command?
ctv does not work when you run it on root because of permissions. 
Try running ctv in your Desktop

**Comment by 0323pin** [comment] 2022-01-26 16:47
I've just run `ctv` without any arguments on my home directory.

**Comment by angelina-tsuboi** [comment] 2022-01-26 16:48
What happens when you run it inside another smaller directory?

**Comment by 0323pin** [comment] 2022-01-26 16:52
I'll get back to you on that later, just went out. Replying from mobile.

**Comment by 0323pin** [comment] 2022-01-26 19:13
@angelina-tsuboi Same result,

![2022-01-26-201140_1366x768_scrot](https://user-images.githubusercontent.com/90570748/151230586-7c3200a8-07e6-43a3-a9af-2e526e780d9f.png)

Compiler warnings during build as follows,

```
   Compiling ctv v0.2.2 (/usr/pkgsrc/wip/ctv/work/ctv-71118d9f4602d993adb4c1aa38b770202ba1049a)
warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:132:17
    |
128 |                   connector = &self.tee;
    |                               --------- immutable borrow occurs here
...
132 | /                 self.add_directory(
133 | |                     entry.path(), entry.path(), index, entries_count, prefix.to_string(), connector.to_string(), limit - 1
    | |                                                                                           --------------------- immutable borrow later used here
134 | |                 )
    | |_________________^ mutable borrow occurs here
    |
    = note: `#[warn(mutable_borrow_reservation_conflict)]` on by default
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:136:17
    |
128 |                 connector = &self.tee;
    |                             --------- immutable borrow occurs here
...
136 |                 self.add_file(entry.path(), prefix.to_string(), connector.to_string())
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------------^
    |                 |                                               |
    |                 |                                               immutable borrow later used here
    |                 mutable borrow occurs here
    |
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: field is never read: `file_perms_color`
  --> src/protocols/file.rs:14:3
   |
14 |   file_perms_color: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `dir_name_style`
  --> src/protocols/file.rs:16:3
   |
16 |   dir_name_style: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `file_name_style`
  --> src/protocols/file.rs:17:3
   |
17 |   file_name_style: String,
   |   ^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `pipe`
  --> src/protocols/treegenerator.rs:11:5
   |
11 |     pipe: String,
   |     ^^^^^^^^^^^^

warning: `ctv` (bin "ctv") generated 6 warnings
    Finished release [optimized] target(s) in 11m 28s

```

**Comment by angelina-tsuboi** [comment] 2022-01-28 15:40
@0323pin Thanks for the feedback! I'll try to fix this ASAP

**Comment by 0323pin** [comment] 2022-01-31 17:21
@angelina-tsuboi I'll build the new release and report back.

> could you try testing it on a MacOS?

Unfortunately I can't do that, I don't have any Apple hardware.

**Comment by angelina-tsuboi** [comment] 2022-01-31 22:28
@levone1 Can you try building ctv v.0.2.4 ? I added some debug statements to help find the problem. Thanks!

**Comment by levone1** [comment] 2022-02-01 00:46
> @levone1 Can you try building ctv v.0.2.4 ? I added some debug statements to help find the problem. Thanks!

0.2.4:

Config file not created. Please visit https:/
/github.com/angelina-tsuboi/ctv/blob/main/REA
DME.md to learn how to set up a config.toml f
ile for CTV
Create a directory called dev.ctv.ctv inside
/home/defaultuser/.config/ctv
Then make a config.toml file inside /home/de
faultuser/.config/ctv
FILE TIME IS NONE
thread 'main' panicked at 'called `Option::un
wrap()` on a `None` value', /home/defaultuser
/.cargo/registry/src/github.com-1ecc6299db9ec
823/ctv-0.2.4/src/services/time.rs:29:17
stack backtrace:
0: rust_begin_unwind
at /rustc/02072b482a8b5357f7fb5e
5637444ae30e423c40/library/std/src/panicking.
rs:498:5
1: core::panicking::panic_fmt
at /rustc/02072b482a8b5357f7fb5e
5637444ae30e423c40/library/core/src/panicking
.rs:107:14
2: core::panicking::panic
at /rustc/02072b482a8b5357f7fb5e
5637444ae30e423c40/library/core/src/panicking
.rs:48:5
3: ctv::services::time::time_created
4: ctv::protocols::file::File::new
5: ctv::protocols::treegenerator::TreeGene
rator::build_tree
6: ctv::protocols::dirtree::DirTree::gen
7: ctv::main
note: Some details are omitted, run with `RUS
T_BACKTRACE=full` for a verbose backtrace.


Interesting thing is that I do have a config file in /home/defaultuser/.config/ctv/dev.ctv.ctv. File is called 'config.toml'

I tried changing permissions, but...

**Comment by 0323pin** [comment] 2022-02-01 05:42
@levone1 on my system, at least with 0.2.2, I had to place the config in `~/.config/ctv/config.toml`, else it would  complain about missing config file.

@angelina-tsuboi I'll build 0.2.4 in a couple of hours from now and report back.

**Comment by 0323pin** [comment] 2022-02-01 07:55
@angelina-tsuboi Alright, `ctv` v0.2.4

Build warning have been reduced to two, as follows:

```
   Compiling ctv v0.2.4 (/usr/pkgsrc/wip/ctv/work/ctv-b2ba94649adb123e2882a12b902dc2f7c8edecfd)
warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:127:17
    |
123 |                   connector = &self.tee;
    |                               --------- immutable borrow occurs here
...
127 | /                 self.add_directory(
128 | |                     entry.path(), entry.path(), index, entries_count, prefix.to_string(), connector.to_string(), limit - 1
    | |                                                                                           --------------------- immutable borrow later used here
129 | |                 )
    | |_________________^ mutable borrow occurs here
    |
    = note: `#[warn(mutable_borrow_reservation_conflict)]` on by default
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:131:17
    |
123 |                 connector = &self.tee;
    |                             --------- immutable borrow occurs here
...
131 |                 self.add_file(entry.path(), prefix.to_string(), connector.to_string())
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------------^
    |                 |                                               |
    |                 |                                               immutable borrow later used here
    |                 mutable borrow occurs here
    |
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: `ctv` (bin "ctv") generated 2 warnings
    Finished release [optimized] target(s) in 12m 00s

```

And a different thread_panic:

```
2022-02-01 08:49 > RUST_BACKTRACE=full ctv ./Documents/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "missing field `file_name_style`", key: [] } }', src/protocols/configmanager.rs:159:47
stack backtrace:
   0:         0xcb4bbd26 - <unknown>
   1:         0xcb4edc5c - <unknown>
   2:         0xcb4b1c95 - <unknown>
   3:         0xcb4b2c70 - <unknown>
   4:         0xcb4b2811 - <unknown>
   5:         0xcb4b32bb - <unknown>
   6:         0xcb4bc490 - <unknown>
   7:         0xcb4bbe74 - <unknown>
   8:         0xcb4b2d62 - <unknown>
   9:         0xcb4154b1 - <unknown>
  10:         0xcb415a13 - <unknown>
  11:         0xcb43c5c6 - <unknown>
  12:         0xcb44281e - <unknown>
  13:         0xcb43de63 - <unknown>
  14:         0xcb446b2d - <unknown>
  15:         0xcb4af311 - <unknown>
  16:         0xcb446002 - <unknown>
  17:         0xcb410a5d - <unknown>
error: External command failed
  ┌─ shell:6:21
  │
6 │ RUST_BACKTRACE=full ctv ./Documents/
  │                     ^^^ command failed


```

**Comment by angelina-tsuboi** [comment] 2022-02-02 21:02
@0323pin interesting... what do you have in your **config.toml** file?

**Comment by 0323pin** [comment] 2022-02-02 21:46
The default config from the  README.md file.

**Comment by angelina-tsuboi** [comment] 2022-02-08 07:02
> Interesting thing is that I do have a config file in /home/defaultuser/.config/ctv/dev.ctv.ctv. File is called 'config.toml'
@levone1 
Interesting... The printed colored error instructions might have been wrong. I changed up the code for the config and made a change that might solve the `Option::unwrap() on a None value` error temporarily. 

The version is ctv v.0.2.5 please try it out, and let me know if anything changes. Thank you!

**Comment by angelina-tsuboi** [comment] 2022-02-08 07:06
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "missing field `file_name_style`", key: [] } }', src/protocols/configmanager.rs:159:47
> stack backtrace:

@0323pin I think that might be an issue inside your **config.toml** file... 
The **file_name_style** property in your config.toml should be set to **"NORMAL"**
So the field in your config.toml should look like:
`file_name_style="NORMAL"`
Can you try checking the values inside the config.toml, and seeing if anything is wrong.
Please let me know. Thank you!

**Comment by 0323pin** [comment] 2022-02-08 13:14
@angelina-tsuboi There's no reference to this on the example config. Adding it actually makes it work 😄 

Nearly there!
![2022-02-08-141043_845x440_scrot](https://user-images.githubusercontent.com/90570748/152993974-748ba82f-14a2-4d8f-ae62-1ab00c3df11a.png)

Why is it printing `FILE TIME IS NONE` for every single entry before actually displaying the output?

**Comment by angelina-tsuboi** [comment] 2022-02-08 22:15
@0323pin Great, that it almost worked! The `FILE TIME IS NONE` print was just a debug printout to figure out what was going on.

I think I was able to fix it!! Please test out **ctv v.0.2.7** and let me know if it works. Thank you :)

**Comment by 0323pin** [comment] 2022-02-08 22:36
@angelina-tsuboi I think I should try it on a _"normal"_ shell also, as somethings can behave weird on `nushell`, which I'm using.

I'll build 0.2.7 in the morning, it's really late now and it's a working day tomorrow.

If all it's fine, I would like to merge the package into the main branch of pkgsrc, https://www.pkgsrc.org/#index4h1

Could I ask you to please keep github release tags in sync with crates.io releases? That makes it easier for me to keep track of updates and new releases. Thanks.

**Comment by angelina-tsuboi** [comment] 2022-02-08 23:13
@0323pin Sounds good. Thanks! Let me know how v0.2.7 works once you're able to get to it in the morning. 
It would be amazing if you could merge ctv into pkgsrc!
Apologies for not keeping the github release tags up to date with the crate.io releases.
I will make sure to do that for all the upcoming versions. I just made a github release for **v0.2.7**
Thanks again!

**Comment by 0323pin** [comment] 2022-02-09 07:18
@angelina-tsuboi  Really close now 🥳 

Two things,
-Date/time stamps
![2022-02-09-081403_737x415_scrot](https://user-images.githubusercontent.com/90570748/153140537-6bd8da32-ea1a-45b8-ba88-8df810212b58.png)

-Build warnings that could cause issues when lang/rust moves forward,
```
   Compiling ctv v0.2.7 (/usr/pkgsrc/wip/ctv/work/ctv-0.2.7)
warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:127:17
    |
123 |                   connector = &self.tee;
    |                               --------- immutable borrow occurs here
...
127 | /                 self.add_directory(
128 | |                     entry.path(), entry.path(), index, entries_count, prefix.to_string(), connector.to_string(), limit - 1
    | |                                                                                           --------------------- immutable borrow later used here
129 | |                 )
    | |_________________^ mutable borrow occurs here
    |
    = note: `#[warn(mutable_borrow_reservation_conflict)]` on by default
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/protocols/treegenerator.rs:131:17
    |
123 |                 connector = &self.tee;
    |                             --------- immutable borrow occurs here
...
131 |                 self.add_file(entry.path(), prefix.to_string(), connector.to_string())
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------------^
    |                 |                                               |
    |                 |                                               immutable borrow later used here
    |                 mutable borrow occurs here
    |
    = warning: this borrowing pattern was not meant to be accepted, and may become a hard error in the future
    = note: for more information, see issue #59159 <https://github.com/rust-lang/rust/issues/59159>

warning: `ctv` (bin "ctv") generated 2 warnings
    Finished release [optimized] target(s) in 11m 42s

```
 Thanks for the awesome work.

**Comment by angelina-tsuboi** [comment] 2022-02-09 14:38
@0323pin Awesome! 🎉 I'll try to fix the build warnings and the time/date displays.
The date/time bug might possibly be due to the fact that you might be using an unsupported platform.
See the code below:
```rs
  if filetime::FileTime::from_creation_time(&file.symlink_metadata().unwrap()).is_some() {
    let naive = chrono::NaiveDateTime::from_timestamp(
      filetime::FileTime::from_creation_time(&file.symlink_metadata().unwrap())
      .unwrap()
      .seconds() as i64,
      0,
      );

    let datetime: chrono::DateTime<chrono::Local> =
      chrono::DateTime::from_utc(naive, *chrono::Local::now().offset());
    datetime.format(time_format).to_string()
  } else {
    "00 000 00:00:00".to_string()
  }
```

**Comment by 0323pin** [comment] 2022-02-09 15:01
@angelina-tsuboi I don't think so. If you see above on one of my screenshots, https://github.com/angelina-tsuboi/ctv/issues/1#issuecomment-1022510924 you will see the time and date on the status bar.

I'm using `leftwm` a window manager written in Rust and the time and date come from `chrono`. Although they are trying to shift over to use `time` due to the unfixed CVE in `chrono`, https://rustsec.org/advisories/RUSTSEC-2020-0159

**Comment by 0323pin** [comment] 2022-02-09 16:48
@angelina-tsuboi could it be because you're using a rather old version of `libc`?

**Comment by levone1** [comment] 2022-02-10 13:37
0.2.7 working for me with sudo. As normal user, I get panic with permission denied error...

**Comment by angelina-tsuboi** [comment] 2022-02-10 20:15
@0323pin interesting... I'll look into it, and try to figure it out.

**Comment by angelina-tsuboi** [comment] 2022-02-10 20:16
@levone1 I think I might know what's going on. I'll look through the code, and will get back to you

**Comment by angelina-tsuboi** [comment] 2022-02-11 15:43
@levone1 just wondering. what directory do you run the ctv command in? The ctv command will always have permission issues in root. Can you try running it in a smaller directory or on your Desktop? Thanks

**Comment by angelina-tsuboi** [comment] 2022-02-12 16:48
@mattfbacon Awesome! Could you make the appropriate changes to the README, and I'll publish a new version of ctv. 
Then @levone1 can test the new version on his computer.

**Comment by mattfbacon** [comment] 2022-02-12 16:48
#7

**Comment by mattfbacon** [comment] 2022-02-12 17:46
![NetBSD neofetch](https://user-images.githubusercontent.com/58113890/153722207-032d02f6-d413-4540-bfb4-1eb1f376c009.png)

![ctv working on NetBSD](https://user-images.githubusercontent.com/58113890/153722214-f357b02e-2b61-4682-bd2b-b2d969f85725.png)

**Comment by 0323pin** [comment] 2022-02-12 18:04
Awesome.
I'll build a new package soon and merge it if everything is good.

I'll post here once it's done.

**Comment by 0323pin** [comment] 2022-02-12 18:05
@angelina-tsuboi could you provide a fresh release tag, please.

**Comment by mattfbacon** [comment] 2022-02-12 18:05
In the meantime you can also use `cargo install --git https://github.com/mattfbacon/ctv`

**Comment by angelina-tsuboi** [comment] 2022-02-12 18:06
@0323pin I'm building and publishing a new release right now. Give me a couple of minutes

**Comment by 0323pin** [comment] 2022-02-12 20:20
@angelina-tsuboi Thanks, I'll get the package done by tomorrow.

@mattfbacon
> In the meantime you can also use cargo install --git https://github.com/mattfbacon/ctv

This is ok for local use, not as a native package which is what I have in mind.
Thanks for jumping in and fixing these issues.

**Comment by levone1** [comment] 2022-02-12 20:21
New version fails to build for me...

`error[E0308]: mismatched types
--> /home/defaultuser/.cargo/registry/src
/github.com-1ecc6299db9ec823/ctv-0.3.2/src/
services/perms.rs:57:38
|
57 |     let user = PermType::User.format(m
ode as u16, colors);
|                                      ^
^^^^^^^^^^ expected `u32`, found `u16`
|
help: you can convert a `u16` to a `u32`
|
57 |     let user = PermType::User.format((
mode as u16).into(), colors);
|                                      +
++++++++

error[E0308]: mismatched types
--> /home/defaultuser/.cargo/registry/src
/github.com-1ecc6299db9ec823/ctv-0.3.2/src/
services/perms.rs:58:40
|
58 |     let group = PermType::Group.format
(mode as u16, colors);
|
^^^^^^^^^^^ expected `u32`, found `u16`
|
help: you can convert a `u16` to a `u32`
|
58 |     let group = PermType::Group.format
((mode as u16).into(), colors);
|
+           ++++++++

error[E0308]: mismatched types
--> /home/defaultuser/.cargo/registry/src
/github.com-1ecc6299db9ec823/ctv-0.3.2/sr`

etc...

**Comment by mattfbacon** [comment] 2022-02-12 21:04
#10

**Comment by angelina-tsuboi** [comment] 2022-02-12 21:48
@mattfbacon When I try to build ctv with the most recent changes, I get the following error
<img width="740" alt="Screen Shot 2022-02-12 at 1 45 38 PM" src="https://user-images.githubusercontent.com/51937266/153729533-8ff18e64-c9fa-4a6c-a46d-06787662947e.png">
:

**Comment by mattfbacon** [comment] 2022-02-12 22:27
OOOOh, probably Linux vs Windows issue??

Anyway, could probably be fixed by adding `as mode_t`.

**Comment by mattfbacon** [comment] 2022-02-12 22:28
Sorry about that, maybe we should add build CI/CD for multiple platforms?

**Comment by mattfbacon** [comment] 2022-02-13 02:37
Just opened a PR for CI. Also fixed the `mode_t` issue.

**Comment by 0323pin** [comment] 2022-02-13 08:33
Merged into pkgsrc, https://mail-index.netbsd.org/pkgsrc-changes/2022/02/13/msg248920.html

**Comment by levone1** [comment] 2022-02-13 11:41
> @mattfbacon Awesome! Thank you so much. I just merged it and released another version **0.3.3** @levone1 Could you try building ctv v0.3.3 and see that works for you?

Issue with config file is fixed - no more error, but still works only with sudo...

**Comment by levone1** [comment] 2022-02-13 13:41
> @mattfbacon Awesome! Thank you so much. I just merged it and released another version **0.3.3** @levone1 Could you try building ctv v0.3.3 and see that works for you?

edit - never mind... Mh fault, (dumb mistake).  Working fine now, tbank you ...

**Comment by angelina-tsuboi** [comment] 2022-02-13 14:59
> Merged into pkgsrc, https://mail-index.netbsd.org/pkgsrc-changes/2022/02/13/msg248920.html

@0323pin Thank you so much! This is super exciting.
@levone1 Glad it worked for you

**Comment by mattfbacon** [comment] 2022-02-13 17:52
I'm curious why winapi is included in the crate dependencies.

**Closed** 2022-02-13 19:11 UTC
Labels: bug, help wanted
